accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/',views.signup,name='signup'),
    path('update/',views.update,name='update'),
    path('delete/',views.delete,name='delete'),
    
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('',views.index,name='index'),
    path('create/',views.create,name='create'),
    path('<int:pk>/detail/',views.detail,name='detail'),
    path('<int:pk>/update/',views.update,name='update'),
    path('<int:pk>/delete/',views.delete,name='delete'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('<int:user_pk>/password/',views.change_password,name='change_password'),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pass

movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(blank=True)
    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm,UserCreationForm


class CustomUserChangeForm(UserChangeForm):
    
    class Meta(UserChangeForm.Meta):
       
        model = get_user_model()
        fields = ('email','first_name','last_name','username')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        password = self.fields.get("password")
        if password:
            password.help_text = ''
        print(password.label)

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username','email','first_name','last_name')

movies/forms.py
from django import forms
from .models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm
from django.views.decorators.http import require_POST, require_http_methods
from .forms import CustomUserCreationForm,CustomUserChangeForm
from django.contrib.auth import update_session_auth_hash

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request,form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else : 
        form = AuthenticationForm()
    context = {
        'form' :form,
    }
    return render(request, 'accounts/login.html',context)
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
        return redirect('movies:index')
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('movies:index')
    else : 
        form = CustomUserCreationForm()
    context = {
        'form' : form,
    }
    return render(request,'accounts/signup.html',context)

def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')

def change_password(request,user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user=form.save()
            update_session_auth_hash(request,user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)

    context = {
        'form' : form,
    }
    return render(request,'accounts/change_password.html',context)

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form,
    }

    return render(request,'accounts/update.html',context)

movies/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Movie
from .forms import MovieForm
from django.views.decorators.http import require_POST, require_http_methods, require_safe
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies' : movies,
    }
    return render(request,'movies/index.html',context)

@login_required
def create(request):
    if request.method=='POST':
        form = MovieForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
        return redirect('movies:index')
    
    else:
        form = MovieForm()

    context = {
        'form' : form,
    }
    return render(request,'movies/create.html',context)
@login_required
def detail(request,pk):
    movie = get_object_or_404(Movie,pk=pk)
    context = {
        'movie' : movie,
    }
    return render(request,'movies/detail.html',context)
@login_required
def update(request,pk):
    movie = get_object_or_404(Movie,pk=pk)
    if request.method=='POST':
        form = MovieForm(request.POST,request.FILES, instance=movie)
        if form.is_valid():
            form.save()
        return redirect('movies:detail',movie.pk)
    
    else:
        form = MovieForm(instance=movie)

    context = {
        'form' : form,
        'movie' : movie,
    }
    return render(request,'movies/update.html',context)

def delete(request,pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')

accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% block content %}
<h1>PASSWORD CHANGE</h1>
<form action="{% url "change_password" user.pk %}" method='POST'>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value='비밀번호 변경'>
</form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<h1>LOGIN PAGE</h1>
<form action="{% url "accounts:login" %}" method='POST'>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value='로그인'>

</form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% block content %}
<h1>SIGNUP PAGE</h1>
<form action="{% url "accounts:signup" %}" method='POST'>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value='회원가입'>
</form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends "base.html" %}
{% block content %}
<h1>UPDATE PAGE</h1>
<form action="{% url "accounts:update" %}" method='POST'>
  {% csrf_token %}
  {% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        
        {% if field.label != "Password" %}
        {{ field.label_tag }} 111 {{ field }}
        {% endif %}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}
  <input type="submit" value='수정'>
</form>
<form action="{% url "accounts:delete" %}" method='POST'>
  {% csrf_token %}
  <input type="submit" value='회원탈퇴'>
</form>
<form action="{% url 'change_password' user.pk%}" method='POST'>
  {% csrf_token %}
  <input type="submit" value='비밀번호변경'>
</form>
{% endblock content %}

movies/templates/movies/create.html
{% extends "base.html" %}
{% block content %}
<h1>CREATE</h1>
<form action="" method='POST' enctype='multipart/form-data'>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

{% endblock content %}

movies/templates/movies/detail.html
{% extends "base.html" %}
{% block content %}
<h1>DETAIL PAGE</h1>
<img src="{{movie.image.url}}" alt="" style='width:400px;height:500px;'>
<h2>{{movie.title}}</h2>
<h3>{{movie.content}}</h3>
{% if movie.image %}

{% endif %}
<a href="{% url "movies:update" movie.pk %}"><button class='btn btn-secondary'>UPDATE</button></a>
<a href="{% url "movies:delete" movie.pk %}"><button class='btn btn-danger'>DELETE</button></a>
<a href="{% url "movies:index" %}" class='btn btn-primary'>back</a>
{% endblock content %}

movies/templates/movies/index.html
{% extends "base.html" %}
{% block content %}
<h1>INDEX PAGE</h1>
<div class="row">
{% for movie in movies  %}

  <div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
      
      <div class="card-body">
        <h5 class="card-title">{{movie.title}}</h5>
        <p class="card-text">{{movie.content}}</p>
        <a href="{% url "movies:detail" movie.pk%}" class="btn btn-primary">Detail</a>
      </div>
    </div>
  </div>

 
  



{% endfor %}
</div>
{% endblock content %}

movies/templates/movies/update.html
{% extends "base.html" %}
{% block content %}
<h1>Update</h1>
<form action="{% url "movies:update" movie.pk %} " method='POST'>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
  {% if request.user.is_authenticated %}
  <nav class="navbar  navbar-expand-lg bg-body-tertiary " data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "movies:index" %}">INDEX</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "movies:create" %}">CREATE</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:update" %}">회원정보수정</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "change_password" user.pk %}">비밀번호변경</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:logout" %}">로그아웃</a>
          </li>
          
          
        </ul>
      </div>
    </div>
  </nav>
  {% else %}
  <nav class="navbar  navbar-expand-lg bg-body-tertiary " data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url "movies:index" %}">SSAFY</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "movies:index" %}">INDEX</a>
          </li>
         
          <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:signup" %}">회원가입</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:login" %}">로그인</a>
          </li>
         
          
          
        </ul>
      </div>
    </div>
  </nav>
  {% endif %}
  {% block content %}
  
  {% endblock content %}


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>